### ISSUE TITLE
prevent clipboard paste when dragging with middle button on linux

### ISSUE THREAD

**Issue by jedediah** [jedediah/wetbanana#19]
looking into it but might not be fixable

**Comment by chastell** [comment]
I still have this with the current devel version (Wet Banana 0.3.999.6) on Chrome 5.0.366.2 on Linux.

**Comment by jedediah** [comment]
oops forgot to push

pull and try now

**Comment by chastell** [comment]
Thanks – much better. Consider it fixed. :)
