### ISSUE TITLE
Right mouse button does not work in Wet Banana 0.3.999.6

### ISSUE THREAD

**Issue by chastell** [jedediah/wetbanana#21]
Setting the button to right does not allow to scoll with the right mouse button in Wet Banana 0.3.999.6 version on Chrome 5.0.366.2 on Linux (while it works fine in Wet Banana 0.3.6).

The console first says it did save the button: "2", but a subsequent attempt to scoll with the right mouse button shows the context menu and the console says ‘wrong button, ignoring ev.button=0 options.button=2’. Sometimes it says ‘WARNING: illegal activity for mousedown: CLICK’.

**Comment by jedediah** [comment]
The tab might be running the old version of the plugin. Try reloading the page after you install or upgrade. I haven't found a way to inject into tabs that are already open when the extension is installed. I might be able to inject an update but I'm not sure about that yet.

**Comment by chastell** [comment]
Hm, I had this issue on the Wet Banana’s options tab, with (I’m almost sure) the old version uninstalled and Chrome restarted. Alas, I cannot replicate this after the upgrade to the version with fixed middle button, so please consider this issue as ‘cannot reproduce’.
