### ISSUE TITLE
Broken by a recent Chrome update (as of 10.0.648.82)

### ISSUE THREAD

**Issue by gjuggler** [jedediah/wetbanana#30]
The extension seems to have been broken by a recent Chrome beta update. I'm on 64-bit Linux (Ubuntu 10.10) and Chrome 10.0.648.82 . When I start to 'grab and drag', the page slides for a fraction of a second before stopping again. No change in the settings seems to fix the problem...

**Comment by jedediah** [comment]
Does this happen to you on all pages? I've seen this before on the occasional page, but it's rare.

**Comment by gjuggler** [comment]
Yep, it's on all pages. Rebooting, clearing cache doesn't work.

I fired up the Javascript console on a whim, and the following error is thrown several dozen times when I try to drag, until the dragging stops working. Perhaps it's got something to do with it?

Uncaught TypeError: Cannot set property 'scrollLeft' of null
  setScroll
  updateScrollPosition
  onMouseMove
chrome-extension://ljecomdaijmibecakcpjadigpfkollbh/content.js:181
chrome-extension://ljecomdaijmibecakcpjadigpfkollbh/content.js:209

**Comment by kenrob2** [comment]
G'day,

## I hate being a' me to', but I agree that it's now broken.  Chrome 11.0.686.0 on XPSP3.  Sorry I don't know when it broke, I haven't played with Chrome for a couple of months.

Regards  
Ken

**Comment by kenrob2** [comment]
(Sorry, didn't mean to shout.  Markdown strikes again.)

## 

Regards  
Ken

**Comment by jedediah** [comment]
Thanks folks. When I get over the flu, I'll grab the latest Chrome beta and take a look at this.

**Comment by jedediah** [comment]
Ok, I fought back the flu symptoms and pushed a new version to the gallery. Remain still while your browser is updated.

**Comment by gjuggler** [comment]
Fantastic -- works great now. Thanks for the quick fix!
