### ISSUE TITLE
Big page jumps around...

### ISSUE THREAD

**Issue by epitron** [jedediah/wetbanana#31]
Odd little glitch... No matter what I set the scalefactor to, this page lags and jumps around when I scroll:

http://hackage.haskell.org/packages/archive/pkg-list.html

(I'm using WetBanana v0.4.1 and the latest Chrome 12 build for Linux.)

What seems to be happening is there's a big lag before it starts to move the page.... and if I move the mouse during that period, it misses those events, and gets confused when I release the mouse.

**Comment by jedediah** [comment]
Occasionally a big page like this will cause a delay when changing the cursor. There is an option to disable cursor changes in WB which works around this. It seems to be a chrome bug so I don't know what else I can do.

**Comment by epitron** [comment]
Ah, interesting. There must be some pretty kludgy hack inside Chrome that changes the cursor. Have you filed a bug on Chromium's issue tracker?
