### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by scarlac** [jedediah/wetbanana#37]
Hi jedediah

I've forked your extension and modified it to work with Safari. This is the only way I could get a hold of you.
Would you mind if I submit it to the extension to Apples extension gallery? I can't tell what license your project is under, since it doesn't say in the code or on github.

Regards
Seph

**Comment by scarlac** [comment]
bump?

**Comment by jedediah** [comment]
Yes, go ahead. I hadn't thought about the license but it will be something that at least allows derived projects that are also open source.

**Comment by scarlac** [comment]
Cool, thx :-)
